### ISSUE TITLE
"repo trigger" test in triggers/repo.js fails when "per_page=100".

### ISSUE THREAD

**Issue by harisibrahimkv** [zapier/zapier-platform-example-app-github#12]
Not an expert here, but while trying out the tutorial at `https://zapier.com/developer/start/testing-your-app`, I got stuck at the `zapier test` step on the `repo trigger` step with the following error:

```
1) repo trigger
       should get a repo:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/haris/zapier/zapier-platform-example-app-github/test/repo.js)
```

Changing the `per_page` query param to just 10 fixed it (in `triggers/repo.js`), but thought of just letting you folks know. :)

Cheers.

**Comment by eliangcs** [comment]
@harisibrahimkv I think you can fix it by increasing the mocha request time limit. So at this line: https://github.com/zapier/zapier-platform-example-app-github/blob/5fc83618d7b057e2a2ea6de5f214f87e3733cfc1/package.json#L11

You can replace it with `node node_modules/mocha/bin/mocha --recursive -t 10000` to increase the limit to 10 seconds.

**Comment by harisibrahimkv** [comment]
@eliangcs That works. Thanks!
